# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Atomic Theory
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The home for FIRST Tech Challenge Team 4174 Atomic Theory 
  on the Information Superhighway.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.atomictheory.xyz" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  davish

# Build settings
markdown: kramdown
